Adding Spin Trigger MQTT documentation
spinkube/documentation pull request #167
Opened 2024-05-23 04:29 UTC by tpmccallum

2024-05-24 01:21 UTC, tpmccallum reviewed
Removing blank lines

2024-05-24 01:21 UTC, tpmccallum commented on content/en/docs/spin-trigger-mqtt/installation/_index.md
> +
```suggestion
```

2024-05-24 01:21 UTC, tpmccallum commented on content/en/docs/spin-trigger-mqtt/installation/_index.md
> +
```suggestion
```

2024-05-24 01:21 UTC, tpmccallum commented on content/en/docs/spin-trigger-mqtt/installation/_index.md
> +>
```suggestion
```

2024-05-28 10:27 UTC, endocrimes requested changes

2024-05-28 10:27 UTC, endocrimes commented on content/en/docs/spin-trigger-mqtt/contributing/_index.md
> +* Open the repository in Dev Container or in the pre-configured GitHub [Codespace](https://codespaces.new/spinkube/spin-trigger-mqtt).
```suggestion
* Open the repository in a Dev Container or in the pre-configured GitHub [Codespace](https://codespaces.new/spinkube/spin-trigger-mqtt).
```

we should include non-devcontainer instructions for setup too - devcontainers are kinda inherently tied to vscode.

2024-05-28 10:27 UTC, endocrimes commented on content/en/docs/spin-trigger-mqtt/installation/_index.md
> +tags: [plugins, MQTT, spin]
```suggestion
tags: [plugins, MQTT]
```

Spin is somewhat implicit 😅

2024-05-28 10:27 UTC, endocrimes commented on content/en/docs/spin-trigger-mqtt/installation/_index.md
> +title: Installation
```suggestion
title: Local installation
```

The default expectation in spinkube is that you'd be installing on Kubernetes

2024-05-28 10:27 UTC, endocrimes commented on content/en/docs/spin-trigger-mqtt/contributing/_index.md
> +tags: [contributing, plugins, mqtt]
```suggestion
tags: [plugins, mqtt]
```

repeating categories in tags leads to neither really making sense 😅

2024-05-28 10:27 UTC, endocrimes commented on content/en/docs/spin-trigger-mqtt/_index.md
> +[Spin Trigger MQTT](https://github.com/spinkube/spin-trigger-mqtt/) is an MQTT trigger designed specifically for Spin. It enables seamless integration between Spin and MQTT-based systems, allowing yo
```suggestion
[Spin Trigger MQTT](https://github.com/spinkube/spin-trigger-mqtt/) is an MQTT trigger designed specifically for Spin. It enables seamless integration between Spin and MQTT-based systems, allowing you to automate workflows and trigger actions based on MQTT messages. With Spin Trigger MQTT, you can easily connect Spin with MQTT brokers and subscribe to topics of interest. When a message is received on a subscribed topic, Spin Trigger MQTT triggers the associated component. This documentation provides a guide on how to set up and use Spin Trigger MQTT, empowering you to leverage the power of MQTT in your Spin applications.
```

2024-05-28 10:27 UTC, endocrimes commented on content/en/docs/spin-trigger-mqtt/_index.md
> +[Spin Trigger MQTT](https://github.com/spinkube/spin-trigger-mqtt/) is an MQTT trigger designed specifically for Spin. It enables seamless integration between Spin and MQTT-based systems, allowing yo
(we don't have any inherent workflow automation or tooling for business process management - they are much higher level tools than Spin.)

2024-05-29 00:44 UTC, tpmccallum commented
Thanks for the inline review comments @endocrimes

2024-05-30 12:01 UTC, endocrimes approved these changes
lgtm, one nit

2024-05-30 12:01 UTC, endocrimes commented on content/en/docs/spin-trigger-mqtt/contributing/_index.md
> +* Run `mqttx pub -t 'messages-in01' -h '<mqtt server ip>' -p 1883 -u <user> -P <password> -m 'Hello to  MQTT Spin Component!'` with the hostname and credentials for your server, to publish the messag
```suggestion
* Run `mqttx pub -t 'messages-in01' -h '<mqtt server ip>' -p 1883 -u <user> -P <password> -m 'Hello MQTT Spin Component!'` with the hostname and credentials for your server, to publish the message which is then received by Spin app.
```

2024-05-31 02:17 UTC, tpmccallum commented
Thank you, Danielle!
Got that last inline commit in and am merging now :partying_face:

2024-05-31 02:17 UTC, merged