Selective Deployments Tutorial
spinkube/documentation pull request #259
Opened 2024-11-08 03:59 UTC by macolso

A basic tutorial that walks users through how to scaffold and run a selective deployment using the salutations sample app from @kate-goldenring . 

Few outstanding todos
 - [ ] Update Spin App CR once salutations OCI artifact gets revved
 - [ ] Check that the formatting on `spin kube scaffold --component` is correct. It currently doesn't match what we've been using manually (@bacongobbler ). I could be making a mistake somewhere along the way
 - [ ] Include output from port forwarding test at the end 
 
 Resolves #258

2024-11-08 16:02 UTC, kate-goldenring requested changes
All the texts looks great -- only nits. Only blocker is the shim version needs to change

2024-11-08 16:02 UTC, kate-goldenring commented on content/en/docs/topics/selective-deployments.md
> +And there you have it! A subset of your Spin application deployed on SpinKube with no modifications to your source code. This approach lets you quickly deploy only the components you need, which can
```suggestion
And there you have it! You selectively deployed a subset of your Spin application to SpinKube with no modifications to your source code. This approach lets you easily deploy only the components you need, which can improve efficiency in environments where only specific services are required.
```

2024-11-08 23:22 UTC, kate-goldenring approved these changes

2024-11-10 20:52 UTC, macolso commented on content/en/docs/topics/selective-deployments.md
> +  image: "ghcr.io/spinkube/spin-operator/salutations:20241105-223428-g4da3171"
NVM - I thought I saw a TODO in the app directory but you're right it's good to go.

2024-11-10 21:24 UTC, merged